"""Adding settings field to User model

Revision ID: 22b92cd2b1ed
Revises: ba3fdb3b8bf9
Create Date: 2024-01-29 02:47:32.766162

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22b92cd2b1ed'
down_revision: str | None = 'ba3fdb3b8bf9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('settings', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'settings')
    # ### end Alembic commands ###
