"""Adding language field to User model

Revision ID: 483da21553f1
Revises: 931f6407b099
Create Date: 2024-02-06 01:41:50.467930

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '483da21553f1'
down_revision: str | None = '931f6407b099'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language', sa.String(), nullable=True))
    op.execute(sa.text("""update users set language = 'en'"""))
    op.alter_column("users", "language", existing_nullable=True, nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')
    # ### end Alembic commands ###
