"""Adding home_link field to Source model

Revision ID: 83e7121e2bf2
Revises: b5096d57700a
Create Date: 2024-01-29 03:43:37.530631

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '83e7121e2bf2'
down_revision: str | None = 'b5096d57700a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('home_link', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'home_link')
    # ### end Alembic commands ###
