"""Adding unique constraint to Source model

Revision ID: ba3fdb3b8bf9
Revises: c88f5a91966a
Create Date: 2024-01-27 22:26:30.912970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba3fdb3b8bf9'
down_revision: Union[str, None] = 'c88f5a91966a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('source_user_link_uc', 'sources', ['user_id', 'link'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('source_user_link_uc', 'sources', type_='unique')
    # ### end Alembic commands ###
